# Generated by Django 2.1.4 on 2018-12-10 14:28

from django.db import migrations, models
import djongo.models.fields
import serinus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.Sensor, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.MetaData, null=True)),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumidityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.Sensor, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.MetaData, null=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=50)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LightRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.Sensor, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.MetaData, null=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=50)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.Sensor, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.MetaData, null=True)),
                ('value', models.BooleanField()),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoiseRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.Sensor, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.MetaData, null=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=50)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vicinity_oid', models.UUIDField(default=None)),
                ('origin_id', models.GenericIPAddressField(protocol='IPv4')),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.Sensor, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.MetaData, null=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=50)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
