# Generated by Django 2.1.4 on 2018-12-09 18:12

from django.db import migrations, models
import djongo.models.fields
import serinus.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CO2Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.Sensor, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.MetaData, null=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DecimalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.Sensor, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.MetaData, null=True)),
                ('value', models.DecimalField(decimal_places=10, max_digits=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MovementRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.Sensor, null=True)),
                ('meta_data', djongo.models.fields.EmbeddedModelField(model_container=serinus.models.MetaData, null=True)),
                ('value', models.BooleanField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
